# Game
NUMBER_OF_CHARACTERS = 7
CARDS_IN_GAME = 30
LAST_DAY = 26

# Cards
EXPEDITE_CARDS = 3
FIRST_HALF_APPEARS = 5
SECOND_HALF_APPEARS = 12
FIRST_EXPEDITE = 8
SECOND_EXPEDITE = 13
THIRD_EXPEDITE = 16

# Effort
MIN_TEAM_EFFORT = 2
MAX_TEAM_EFFORT = 6