# Generated by Django 3.0.7 on 2021-06-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='analytic_points',
            new_name='analytic_completed',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='analytic_size',
            new_name='analytic_remaining',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='develop_point',
            new_name='develop_completed',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='develop_size',
            new_name='develop_remaining',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='test_point',
            new_name='test_completed',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='test_size',
            new_name='test_remaining',
        ),
        migrations.AddField(
            model_name='card',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='is_expedite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='ready_day',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dayNum', models.IntegerField(default=1)),
                ('wip_limit1', models.IntegerField()),
                ('wip_limit2', models.IntegerField()),
                ('wip_limit3', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('effort', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('anl_completed_tasks', models.IntegerField()),
                ('dev_completed_tasks', models.IntegerField()),
                ('test_completed_tasks', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Team')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='board.Team'),
            preserve_default=False,
        ),
    ]
