# Generated by Django 3.0.7 on 2021-06-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210611_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='effort',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
