# Generated by Django 3.0.7 on 2021-06-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210612_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='column_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='row_number',
            field=models.IntegerField(default=0),
        ),
    ]
