# Generated by Django 3.0.7 on 2021-06-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210614_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
