# Generated by Django 3.1.3 on 2021-06-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20210618_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='started',
            new_name='ready',
        ),
    ]
