# Generated by Django 3.1.3 on 2021-06-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_remove_room_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='wip_limit1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='wip_limit2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='wip_limit3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
