# Generated by Django 3.0.7 on 2021-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_room_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='business_value_sum',
            field=models.IntegerField(default=0),
        ),
    ]
